a.(b&c) < (a.b)&(a.c)
(a.b) | ((((a&b).c.d)&(e.(f&g))&h)&i) < ((h&(e.f))&(a.c.d)) | (a.b)
(a&b).((a&b)+) = ((a&b)+).(a&b)
(b&c).a < (b.a)&(c.a)
(a&b).(c&d) = (b&a).(c&d)
(a&b).(a&b).(a&b) | (a&b).(a&b) | (a&b) < ((a&b)+)
(a&b).(a&b).(a&b) <> (a&b).(a&b).(a&b).(a&b)
